# Generated by Django 5.2.4 on 2025-07-25 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('env_vars', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('template', models.CharField(max_length=50)),
                ('plan_type', models.CharField(max_length=20)),
                ('repo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.environment')),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='webapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.webapp'),
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='app.webapp')),
            ],
        ),
    ]
