# Generated by Django 5.2.4 on 2025-07-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='webapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='app.webapp'),
        ),
    ]
