# Generated by Django 5.2.4 on 2025-07-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_environment_webapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentlog',
            name='webapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='app.webapp'),
        ),
    ]
